feat: Remove Top Bar In Mcq Page
CODE-73/learning-app pull request #12
Opened 2024-01-29 11:00 UTC by rameez1010

2024-01-29 17:55 UTC, mohammedfabinsha requested changes
Alignment issue for All Questions and Quit. And pls remove console.log

2024-01-31 08:03 UTC, rameez1010 commented
lint error in this is fixed on #14

2024-02-01 05:55 UTC, mohammedfabinsha approved these changes
Looks good!

2024-02-03 04:48 UTC, mohammedfabinsha approved these changes

2024-02-03 05:55 UTC, merged